- name: install secret fb default namespace
  command: kubectl apply -f /root/secret/sosmed-secret.yml
- name: install secret wp default namespace
  command: kubectl apply -f /root/secret/wp-secret.yml
- name: install secret fb staging namespace
  command: kubectl apply -f /root/secret/sosmed-secret.yml -n=staging
- name: install secret wp staging namespace
  command: kubectl apply -f /root/secret/wp-secret.yml -n=staging
- name: install secret fb production namespace
  command: kubectl apply -f /root/secret/sosmed-secret.yml -n=production
- name: install secret wp production namespace
  command: kubectl apply -f /root/secret/wp-secret.yml -n=production