- name: install prometheus
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
- name: install prometheus
  command: helm repo update
- name: install prometheus
  command: helm install prometheus prometheus-community/prometheus -n=monitoring
- name: helm repo add grafan
  command: helm repo add grafana https://grafana.github.io/helm-charts
- name: helm repo update
  command: helm repo update
- name: install grafana
  command: helm install grafana grafana/grafana -n=monitoring
- name: apply -f grafana-ingress
  command: kubectl apply -f /root/grafana-ingress.yml
- name: apply -f prometheus-ingress
  command: kubectl apply -f /root/prometheus-ingress.yml
